POST http://127.0.0.1:5000/init
Content-Type: application/json

{
    "num_routers":5
}
###
POST http://127.0.0.1:5000/add_link
Content-Type: application/json

{
    "links": [
        {"u": 0, "v": 1, "distance": 1},
        {"u": 1, "v": 2, "distance": 6},
        {"u": 1, "v": 4, "distance": 3},
        {"u": 2, "v": 3, "distance": 2},
        {"u": 3, "v": 4, "distance": 4}
    ]
}

###
GET http://127.0.0.1:5000/initial_routing_table
###
GET http://127.0.0.1:5000/get_routing_table
